name: 'Pull Request'

on:
  pull_request:

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cinch-labs'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Lint
        run: npm run lint:check

      - name: Prettier Check
        run: npm run prettier:check

      - name: Compile TypeScript
        run: npm run build

      - name: Package action
        run: npm run package

      - name: Unit tests
        run: npm run test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Adding an infix
        uses: ./
        with:
          auth-authority: ${{ secrets.AUTH_AUTHORITY }}
          access-key: ${{ secrets.ACCESS_KEY }}
          subdomain-infix: sheepdog

      - name: Removing an infix
        uses: ./
        with:
          auth-authority: ${{ secrets.AUTH_AUTHORITY }}
          access-key: ${{ secrets.ACCESS_KEY }}
          subdomain-infix: sheepdog
          update-type: remove
